server.port: 8081

spring.h2.console:
  enabled: true
  path: /h2-console

# 외부 DB 설정시 아래의 주석을 활성화 시킨 후 관련 DB 설정 정보를 입력한다.
#spring:
#  datasource:
#    url: jdbc:h2:tcp://localhost/~/api;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
#    driverClassName: org.h2.Driver
#    username: sa
#    password:

security:
  oauth2:
    client:
      client-id: foo
      client-secret: bar
    resource:
      jwt.key-uri: http://localhost:8080/oauth/token_key
      # OAuth2 서버에서 열어준 검증용 key 값을 얻어오기 위한 API의 URL을 지정

logging.level:
  org.springframework:
    security: debug
    boot: debug